//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _17599075_PROG7311_POE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CART
    {
        public string USERNAME { get; set; }
        public string ProdID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Cat { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
